//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpId { get; set; }
        public string Name { get; set; }
        public string Desg { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<decimal> salary { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
